# Завдання 1
1, 3, 6, 8, 13, 15, 16, 18, 20

16 20
## Виконати набір вправ. Всі завдання виконати 2 способами:
 <li>з використанням універсальних функцій бібліотеки NumPy</li>
 <li>b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо.</li>

In [ ]:
import math
import random
import numpy as np

## Вправа 1
### Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [ ]:
def task_1():
    n = int(input("Enter n: "))
    arr = [[0 for j in range(n)] for i in range(n)]

    for i in range(n):
        arr[i][i] = i + 1

    for row in arr:
        print(row)


%time task_1()

Enter n:  5


[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
CPU times: total: 0 ns
Wall time: 2.67 s


In [ ]:
import numpy as np

def task_1():
    n = int(input("Enter n: "))
    arr = np.zeros((n, n), dtype=int)
    arr[np.diag_indices_from(arr)] = np.arange(1, n+1)
    print(arr)


%time task_1()

Enter n:  5


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
CPU times: total: 15.6 ms
Wall time: 1.65 s


## Вправа 3
### Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [ ]:
def task_3():
    input_str = input("Enter n, m, r, c separated by space: ")
    values = input_str.split()
    n, m, r, c = map(int, values)

    arr = [[1 for j in range(m)] for i in range(n)]

    for i in range(n):
        if i % r == 0:
            arr[i] = [0 for j in range(m)]

    for i in range(m):
        if i % c == 0:
            for j in range(n):
                arr[j][i] = 0

    for row in arr:
        print(row)

%time task_3()

Enter n, m, r, c separated by space:  6 7 2 3


[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
CPU times: total: 15.6 ms
Wall time: 13.4 s


In [ ]:
import numpy as np

def task_3():
    input_str = input("Enter n, m, r, c separated by space: ")
    values = input_str.split()
    n, m, r, c = map(int, values)

    arr = np.ones((n, m), dtype=int)
    arr[::r, :] = 0
    arr[:, ::c] = 0

    print(arr)

%time task_3()

Enter n, m, r, c separated by space:  6 7 2 3


[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
CPU times: total: 0 ns
Wall time: 3.01 s


## Вправа 6
### З клавіатури вводиться масив, Замінити всі ненульові елементи на -1.

In [ ]:
def task_6(input_array):
    for i in range(len(input_array)):
        if input_array[i] != 0:
            input_array[i] = -1
    return input_array

%time task_6([3,4,0,9,7,0,6,0,4,0,3])

CPU times: total: 0 ns
Wall time: 0 ns


[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]

In [ ]:
import numpy as np

def task_6(input_array):
    arr = np.array(input_array)
    arr[arr != 0] = -1
    return arr

%time task_6([3,4,0,9,7,0,6,0,4,0,3])

CPU times: total: 0 ns
Wall time: 0 ns


array([-1, -1,  0, -1, -1,  0, -1,  0, -1,  0, -1])

## Вправа 8
### З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

In [3]:
import numpy as np
import time
def task8_numpy(arr):
    num_zeros = np.count_nonzero(arr == 0)
    num_nonzeros = np.count_nonzero(arr != 0)
    return num_zeros, num_nonzeros

def task8_iterative(arr):
    num_zeros = sum(1 for x in arr if x == 0)
    num_nonzeros = len(arr) - num_zeros
    return num_zeros, num_nonzeros


arr = np.array(list(map(int, input("Введіть масив чисел через пробіл: ").split())))


start_time_numpy = time.time()
num_zeros_numpy, num_nonzeros_numpy = task8_numpy(arr)
end_time_numpy = time.time()


print("Нулів:", num_zeros_numpy)
print("Не нулів:", num_nonzeros_numpy)
print("Час виконання (NumPy):", end_time_numpy - start_time_numpy, "секунд")


start_time_iterative = time.time()
num_zeros_iterative, num_nonzeros_iterative = task8_iterative(arr)
end_time_iterative = time.time()


print("Нулів:", num_zeros_iterative)
print("Не нулів:", num_nonzeros_iterative)
print("Час виконання (Ітеративно):", end_time_iterative - start_time_iterative, "секунд")

Введіть масив чисел через пробіл: 3 4 0 9 8 2 4 0 8 4 0
Нулів: 3
Не нулів: 8
Час виконання (NumPy): 0.00041484832763671875 секунд
Нулів: 3
Не нулів: 8
Час виконання (Ітеративно): 0.0001246929168701172 секунд


## Вправа 13
### Розмістити на полі 8×8 нулі та одиниці в шахматному порядку, використовуючи функцію повторення (*).

In [4]:
def task13_numpy():
    chessboard = np.zeros((8, 8), dtype=int)
    chessboard[1::2, ::2] = 1
    chessboard[::2, 1::2] = 1
    return chessboard

def task13_iterative():
    chessboard = []
    for i in range(8):
        row = [1 if (i+j) % 2 == 1 else 0 for j in range(8)]
        chessboard.append(row)
    return chessboard


start_time_numpy = time.time()
result_numpy = task13_numpy()
end_time_numpy = time.time()


print("Результат (NumPy):")
print(result_numpy)
print("Час виконання (NumPy):", end_time_numpy - start_time_numpy, "секунд")


start_time_iterative = time.time()
result_iterative = task13_iterative()
end_time_iterative = time.time()


print("\nРезультат (Ітеративно):")
for row in result_iterative:
    print(row)
print("Час виконання (Ітеративно):", end_time_iterative - start_time_iterative, "секунд")

Результат (NumPy):
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Час виконання (NumPy): 0.0006012916564941406 секунд

Результат (Ітеративно):
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
Час виконання (Ітеративно): 9.5367431640625e-05 секунд


## Вправа 15
### Заповнити парні стовпчикі матриці розміром n×n одиницями, а непарні – нулями.

In [ ]:
def task_15(n):
    matrix = [[1 if col % 2 == 0 else 0 for col in range(n)] for row in range(n)]
    return matrix

%timeit task_15(5)

2.17 µs ± 80 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
import numpy as np

def task_15(n):
    matrix = np.zeros((n, n))
    matrix[:, ::2] = 1
    return matrix

%timeit task_15(5)

785 ns ± 17 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Вправа 16
### РЗаповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [5]:
def exercise_16_default(n):
    return [0 if (n / 4 < i < (3 * n) / 4) else i for i in range(n + 1)]


def exercise_16_numpy(n):
    result = np.arange(n + 1)
    result[(result > n / 4) & (result < (3 * n) / 4)] = 0

    return result

n = 10

print("=========Default=========")
%timeit -n 1000 exercise_16_default(n)

print("=========Numpy=========")
%timeit -n 1000 exercise_16_numpy(n)

print("=========Default result=========")
print(exercise_16_default(n))

print("=========Numpy result=========")
print(exercise_16_numpy(n))

=========Default=========
3.98 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
=========Numpy=========
5.5 µs ± 201 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
=========Default result=========
[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
=========Numpy result=========
[ 0  1  2  0  0  0  0  0  8  9 10]


## Вправа 18
### Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [ ]:
def task_18(n):
    array = []
    for i in range(n):
        array.append(random.randint(0, 100))
    print(array)
    list_set = set(array)
    return len(list_set)

%time print("unique values: ", task_18(30))

[49, 66, 96, 5, 90, 56, 79, 0, 36, 8, 0, 58, 73, 48, 32, 46, 71, 3, 56, 1, 20, 76, 73, 29, 42, 50, 97, 74, 38, 54]
unique values:  27
CPU times: total: 0 ns
Wall time: 0 ns


In [ ]:
import numpy as np

def task_18(n):
    array = np.random.randint(0, 100, n)
    print(array)
    return len(np.unique(array))

%time print("unique values: ", task_18(30))

[99 92 92  2 52 44 17  0 80 74 56 41 90 62 62  1 70 32 93 99 31 13 57 30
 29 17 44 86 46 24]
unique values:  25
CPU times: total: 0 ns
Wall time: 1 ms


## Вправа 20
### Згенерувати вектор із n випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [8]:
import random
def task_20(n,f_type):
    def task_default():

        return max([random.random() for _ in range(n)])

    def task_numpy():
        return np.max(np.random.rand(1,n))

    f = {'default': task_default, 'numpy': task_numpy}
    return f[f_type]
def compare_time(f1, f2):
    start = time.time()
    result1 = f1()
    end = time.time()

    print(result1)
    print(f"Execution time: {end - start} seconds")

    start = time.time()
    result2 = f2()
    end = time.time()

    print(result2)
    print(f"Execution time: {end - start} seconds")

    print(f"Results are equal:{np.allclose(result1, result2)}")
compare_time(task_20(10, 'default'), task_20(10, 'numpy'))

0.8848801006787088
Execution time: 1.430511474609375e-05 seconds
0.7663830619011517
Execution time: 0.0008664131164550781 seconds
Results are equal:False


# Task 2

## Завдання 2
### Розв'язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
- матричного множення
- оберненої матриці
- функції numpy.linalg.solve()

### Порівняти всі рішення за допомогою функції numpy.allclose().
### Матричне представлення системи лінійних алгебраїчних рівнянь та розв'язок:

\[
\begin{align*}
2x_1 - 6x_2 + 2x_3 + 2x_4 &= 12 \\
x_1 + 3x_2 + 5x_3 + 7x_4 &= 12 \\
3x_1 + 5x_2 + 7x_3 + 1x_4 &= 0 \\
5x_1 + 7x_2 + 1x_3 + 3x_4 &= 4 \\
\end{align*}
\]
нь та розв'язок:

### Порівняти всі рішення за допомогою функції numpy.allclose().

### Матричне представлення системи лінійних алгебраїчних рівнянь та розв'язок:

In [9]:
left = np.array([
    [2, -6, 2, 2],
    [1,  3, 5, 7],
    [3, 5, 7, 1],
    [5, 7, 1, 3]
])

right = np.array([12, 12, 0, 4])


def cramers_solve(left, right):
    length = len(right)
    determinant = np.linalg.det(left)
    solution = np.zeros(length)

    if np.allclose(determinant, 0):
        print("Determinant is zero, there's no solution of given equation.")
        return solution

    for i in range(length):
        modified_left = np.copy(left)
        modified_left[:, i] = np.copy(right)
        solution[i] = np.linalg.det(modified_left) / determinant

    return solution

cramer_result = cramers_solve(left, right)
numpy_result = np.linalg.solve(left, right)
multiplication_check = np.dot(left, cramer_result)
inverse_matrix_check = np.dot(np.linalg.inv(left), right)

print(f"Result of Cramer's method: {cramer_result}")
print(f"Result of using numpy.linalg.solve(): {numpy_result}")
print(f"Check results: {np.allclose(numpy_result, cramer_result)}\n")

print(f"Check using matrix multiplication: {np.allclose(right, multiplication_check)}")
print(f"Check using inverse matrix: {np.allclose(inverse_matrix_check, cramer_result)}")

Result of Cramer's method: [ 1.00000000e+00 -1.00000000e+00 -9.36750677e-17  2.00000000e+00]
Result of using numpy.linalg.solve(): [ 1.00000000e+00 -1.00000000e+00 -1.01770444e-16  2.00000000e+00]
Check results: True

Check using matrix multiplication: True
Check using inverse matrix: True


# Task 3

# Обчислити значення матричного виразу
$$
3(A + B)(AB - 2A), \quad A =
\begin{bmatrix}
    2 & 1 & 3 \\
    1 & -2 & 0 \\
    4 & -3 & 0 \\
\end{bmatrix},
\quad B =
\begin{bmatrix}
    22 & -14 & 3 \\
    6 & -7 & 0 \\
    11 & 3 & 15 \\
\end{bmatrix}
$$
bmatrix}
\]


- з використанням універсальних функцій бібліотеки NumPy.
- за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
- для обох випадків підрахувати час виконання скрипту та
зробити висновок.

In [10]:
A = [[2, 1, 3],
     [1, -2, 0],
     [4, -3, 0]]

B = [[22, -14, 3],
     [6, -7, 0],
     [11, 3, 15]]

A_np = np.array(A)
B_np = np.array(B)


def multiplication(A, B):
    a_rows, a_columns, b_rows, b_columns = len(A), len(A[0]), len(B), len(B[0])
    result = []
    if a_columns != b_rows:
        print("Multiplication cannot be done because of different dimensions.")
        return result

    for i in range(a_rows):
        new_row = []
        for j in range(b_columns):
            element_sum = 0
            for k in range(a_columns):
                element_sum += A[i][k] * B[k][j]
            new_row.append(element_sum)
        result.append(new_row)

    return result

def addition(A, B):
    a_rows, a_columns, b_rows, b_columns = len(A), len(A[0]), len(B), len(B[0])
    result = []
    if a_rows != b_rows or a_columns != b_columns:
        print("Addition cannot be done because of different dimensions.")
        return result

    for i in range(a_rows):
        new_row = []
        for j in range(a_columns):
            new_row.append(A[i][j] + B[i][j])
        result.append(new_row)

    return result

def scalar_multiplication(a, A):
    result = []
    for i in range(len(A)):
        new_row = []
        for j in range(len(A[0])):
            new_row.append(A[i][j] * a)
        result.append(new_row)

    return result

In [11]:
%%timeit -n 100 -r 10
numpy_result = 3*(A_np + B_np) @ (A_np * B_np -2*A_np)

11.1 µs ± 3.71 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
